### ISSUE TITLE
Eth Settlement

### ISSUE THREAD

**Issue by timgalebach** [blockmason/lndr#12]
Let's add settlement as the next feature after initial release.

**Comment by aupiff** [comment]
Tim's suggested settlement workflow here: https://gist.github.com/timgalebach/162f53c2df89c46c895d40acb71dbebf

**Comment by aupiff** [comment]
Debtor-initiated settlement flow:

A unilateral payment debt is submitted by debtor. Settlement memos are auto-generated and fixed: "s {integer} {eth unit}"

When the complementary debt confirmation is submitted by the creditor, the server records the block number and holds the bilateral debt in limbo. The debtor must then submit a tx hash to the server that points to a tx wherein the indicated amount of eth was transfered from the debtor address to the creditor address. The tx should occur in a block whose number is strictly greater than the one recorded by the server along with the bilateral credit record. If such a tx hash is submitted to the server successfully, the bilateral debt is submitted to the blockchain.

Creditor-initiated settlement flow is similar.

----

I've add new columns to the existing `pending_credits` and `verified_credits` tables in order to distinguish settlement credits from non-settlement credits.

**Comment by timgalebach** [comment]
So basically you'd coordinate the debt settlement on the CP side on server, and then let the relevant client submit a tx, and tell the server when it had completed?

I'm down with that, avoids the server having to store payment txs, which is helpful on a variety of fronts.

**Comment by aupiff** [comment]
@timgalebach Yep that's the process I'm testing right now. Later, we can try something fancier where the server identifies the correct tx automatically.

**Comment by timgalebach** [comment]
This process also generalizes really easily to using any crypto asset for settlement.

**Comment by aupiff** [comment]
Basic version of this code works and is live on the server. The current settlement flow may need to be altered in order to improve UI.
